license-report.md
plugin-base/src/main/kotlin/io/spine/tools/gradle/project/ProjectExtensions.kt
plugin-base/src/test/kotlin/io/spine/tools/gradle/project/ProjectExtensionsTest.kt
pom.xml
version.gradle.kts

This PR extends `Project` with an ability to obtain a list of source set names.

Add `Project.sourceSetNames` extension

---

license-report.md
plugin-base/src/main/java/io/spine/tools/gradle/CodeGenerationAction.java
plugin-base/src/main/java/io/spine/tools/gradle/ProtobufDependencies.java
plugin-base/src/main/kotlin/io/spine/tools/gradle/SourceSetBasedName.kt
plugin-base/src/main/kotlin/io/spine/tools/gradle/SourceSetName.kt
plugin-base/src/main/kotlin/io/spine/tools/gradle/project/ProjectExtensions.kt
plugin-base/src/test/kotlin/io/spine/tools/gradle/SourceSetNameTest.kt
plugin-base/src/test/kotlin/io/spine/tools/gradle/project/GeneratedDirTest.kt
plugin-base/src/test/kotlin/io/spine/tools/gradle/project/ProjectExtensionsTest.kt
pom.xml
tool-base/src/main/java/io/spine/tools/dart/fs/DartFile.java
tool-base/src/main/java/io/spine/tools/dart/fs/ImportStatement.java
tool-base/src/main/java/io/spine/tools/proto/fs/Directory.java
tool-base/src/main/kotlin/io/spine/tools/StandardTypesExtensions.kt
tool-base/src/test/kotlin/io/spine/tools/StandardTypeExtensionsTest.kt
version.gradle.kts

This PR:
* Extracts Kotlin extensions of standard types that do not depend on Gradle API into `io.spine.tools.StandardTypeExtensions`.
* Introduces `Project.protoDirectorySet()` extension function for obtaining a `proto` directory that _may_ be present in the specified source set.
* Bumps `base` dependency.

More standard type extensions

---

license-report.md
plugin-testlib/src/main/kotlin/io/spine/tools/gradle/testing/GradleProject.kt
plugin-testlib/src/main/kotlin/io/spine/tools/gradle/testing/GradleProjectSetup.kt
plugin-testlib/src/main/kotlin/io/spine/tools/gradle/testing/Replacement.kt
plugin-testlib/src/test/kotlin/io/spine/tools/gragle/testing/GradleProjectTest.kt
plugin-testlib/src/test/kotlin/io/spine/tools/gragle/testing/ReplacementTest.kt
plugin-testlib/src/test/resources/gradle_project_test/build.gradle.kts
plugin-testlib/src/test/resources/gradle_project_test/buildSrc/no-replacement.txt
plugin-testlib/src/test/resources/gradle_project_test/src/main/java/acme/replacement.txt
pom.xml
version.gradle.kts

This changeset brings the functionality on additional processing of files involved into `GradleProject` setup.
In particular, it is now possble to replace the tokens formatted like `@my-token@` with some string values:
```kotlin
GradleProject.setupAt(someDir)
// ....
.replace("my-token", "some value")  // Finds all `@my-token@` strings and turns them into `some value`.
```
The contents of `projectDir/buildSrc` are excluded from the replacement process. Such a procedure would make not much sense, as our `buildSrc` files are usually copies of the "real" `buildSrc` files from the parent project. Therefore, they hardly contain any tokens.
The library version is set to `2.0.0-SNAPSHOT.87`.

Allow to replace tokens in test Gradle projects via `GradleProjectSetup`

---

buildSrc/src/main/kotlin/pmd-settings.gradle.kts
license-report.md
pom.xml
tool-base/src/main/kotlin/io/spine/tools/code/Language.kt
tool-base/src/test/java/io/spine/tools/code/LanguageTest.java
tool-base/src/test/kotlin/io/spine/tools/code/LanguageTest.kt
version.gradle.kts

This PR introduces the `Language` and derived types, which originate from ProtoData project. These types will be used in language-specific settings of Model Compiler, and presumably other dev. tools provided by the Spine framework.
The `Language` and derived classes were extended in the following ways:
* A `Language` can have more than one file extension. This is useful for languages like C and C++.
* File extensions exposed by a `Language` are now alphabetically sorted (to ease the diagnostics when debugging).
* A `Language` can be initialized with `Glob` passed directly. If `filePattern` constructor parameter is not specified, the `filePattern` property will be created using the passed file extensions.
* And vice versa, it is possible not to send any file extensions _but_ send a …

Add `Language` types

---

build.gradle.kts
license-report.md
pom.xml
version.gradle.kts

This PR addresses [#362](https://github.com/SpineEventEngine/config/issues/362).
The extra dependency comes from the root project. `pmd` plugin was applied directly to the root, bypassing our `pmd-settings` script, which applies and configures `pmd` on its own. 
In general, we don't need this plugin in the root. As it doesn't have any sources to analyze. Gradle's [manual](https://docs.gradle.org/current/userguide/pmd_plugin.html) doesn't state that it should be applied to the root. Anyway, when needed, it should be done via `pmd-settings`. 
This PR drops a direct applying of `pmd` plugin to the root.
The library version is bumped to `2.0.0-SNAPSHOT.92`.

Deduplicate `pmd` dependency

---

license-report.md
pom.xml
tool-base/src/main/java/io/spine/tools/java/code/TypeSpecWriter.java
version.gradle.kts

As it appears, we have to pass actual space symbols as an `indent(String)` argument when configuring JavaPoet's codegen.
This changeset does precisely that.

Use actual space symbols when specifying the indentation for JavaPoet

---

.github/workflows/detekt-analysis.yml
.idea/misc.xml
buildSrc/src/main/kotlin/deps-between-tasks.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/fs/LazyTempPath.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/github/pages/RepositoryExtensions.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/github/pages/Update.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/protobuf/ProtoTaskExtensions.kt
license-report.md
plugin-base/build.gradle.kts
plugin-base/src/main/java/io/spine/tools/gradle/ProtocPluginName.java
plugin-base/src/test/kotlin/io/spine/tools/gradle/ProtocPluginNameTest.kt
pom.xml
tool-base/build.gradle.kts
version.gradle.kts

This PR adds `kotlin` to the enumeration of `protoc` plugin names.
Dependencies were also updated.

Add `kotlin` as `protoc` plugin

---

license-report.md
plugin-base/src/main/java/io/spine/tools/gradle/project/DependantProject.java
pom.xml
tool-base/src/main/java/io/spine/tools/code/Indent.java
tool-base/src/main/java/io/spine/tools/js/fs/FileName.java
tool-base/src/main/kotlin/io/spine/tools/code/Language.kt
tool-base/src/test/kotlin/io/spine/tools/code/LanguageTest.kt
version.gradle.kts

In this PR we change the `Language` from generating single-line comments to generating multiline, or, more relevantly for us, inline comments.

Generate inline comments

---

buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt
license-report.md
plugin-base/src/main/kotlin/io/spine/tools/gradle/protobuf/ProtobufGradlePluginAdapter.kt
pom.xml
version.gradle.kts

This PR fixes the reflection call to Protobuf Gradle Plugin in v0.9.0+.

Fix adapter for Protobuf Gradle Plugin in new API branch

---

license-report.md
plugin-base/src/main/kotlin/io/spine/tools/gradle/protobuf/ProtobufGradlePluginAdapter.kt
pom.xml
version.gradle.kts

This PR fixes the type of the parameter passed to the `generateProtoTasks` method.

Fix parameter type passed by `ProtobufGradlePluginAdapter` to new API

---

license-report.md
plugin-base/src/main/kotlin/io/spine/tools/gradle/protobuf/ProtobufGradlePluginAdapter.kt
pom.xml
version.gradle.kts

This PR fixes the configuration call to be `configureEach` instead of `forEach` because the latter caused `ConcurrentModificationException`.

Fix iteration over `GenerateProtoTask` tasks

---

.gitignore
license-report.md
plugin-base/src/main/java/io/spine/tools/gradle/ProtocConfigurationPlugin.java
plugin-base/src/main/java/io/spine/tools/gradle/task/GradleTask.java
plugin-base/src/main/kotlin/io/spine/tools/gradle/protobuf/ProtobufGradlePluginAdapter.kt
pom.xml
tool-base/src/main/kotlin/io/spine/tools/code/Language.kt
version.gradle.kts

This PR fixes the issue of `ProtobufGradlePluginAdapter` which did not allow to create Gradle tasks in configuration actions passed to `GenerateProtoTask`s. See [similar issue](https://github.com/avast/gradle-docker-compose-plugin/issues/210) for details. 
Our issue was addressed by iterating over a copy of the collection of these tasks exposed by Protobuf Gradle Plugin.
Other notable changes:
* Additional debug logging was added in the task configuration code.
* Deprecated `SlashCommentLanguage` class was removed.
* Deprecated `ProtocConfigurationPlugin.isTestsTask()` method was removed.

Fix concurrent modification issue in `ProtobufGradlePluginAdapter`

---

buildSrc/src/main/kotlin/module.gradle.kts
license-report.md
plugin-base/build.gradle.kts
plugin-base/src/main/kotlin/io/spine/tools/gradle/LoggerExts.kt
plugin-testlib/build.gradle.kts
pom.xml
version.gradle.kts

This PR suppresses detekt warnings that failed publishing of the previous PR. It still to be understood why locally executed detekt did not spot this issues.
Still, this PR also removes redundant detekt plugin inclusion in favor of one done in the `module` script plugin.

Suppress detekt warnings

---

.idea/kotlinc.xml
buildSrc/src/main/kotlin/io/spine/internal/dependency/ProtoData.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Roaster.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Validation.kt
license-report.md
plugin-base/src/main/java/io/spine/tools/gradle/Artifact.java
plugin-base/src/test/kotlin/io/spine/tools/gradle/ArtifactSpec.kt
pom.xml
version.gradle.kts

This PR exposes properties of `Artifact` so that we can use them when matching against already added dependencies without parsing the string representation given by the `notion()` method.

Expose `Artifact` properties

---

.idea/kotlinc.xml
build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/io/spine/internal/dependency/IntelliJ.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Kotlin.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/KotlinX.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/ProtoData.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/Repositories.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/protobuf/ProtoTaskExtensions.kt
buildSrc/src/main/kotlin/module.gradle.kts
dependencies.md
pom.xml
version.gradle.kts

This changeset migrates the library to the latest dependencies and script versions from `config`.
In particular, it brings a more consistent strategy on descriptor set generation (`... .desc` and `desc.ref` files). See [config#504](https://github.com/SpineEventEngine/config/pull/504) for more details on that.

Update descriptor set generation

---

buildSrc/src/main/kotlin/DokkaExts.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/ProtoData.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Validation.kt
dependencies.md
pom.xml
tool-base/build.gradle.kts
tool-base/src/main/proto/spine/tools/java/java.proto
tool-base/src/main/proto/spine/tools/proto/proto.proto
version.gradle.kts

This PR removes validation constraints previously added to Protobuf types in the `tool-base` module. Since `tool-base` uses vanilla Protobuf codegen (and not McJava), validation options have no effect, and are simply misleading.
Also the PR removes the redundant `implementation` dependency of `tool-base` on `spine-validation-java-runtime`.
The dependency caused version confusion in sub-projects that depend on `tool-base`.
The dependency on `spine-base` is still relevant for having the `(type_url_prefix)` file option, which is used by Spine utilities for working for packing messages into Protobuf `Any`.
`config` was also updated.

Remove dependency on Validation runtime

---

buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Validation.kt
dependencies.md
plugin-testlib/src/main/kotlin/io/spine/tools/gradle/testing/GradleProject.kt
pom.xml
psi-java/src/main/kotlin/io/spine/tools/psi/java/PsiJavaAppEnvironment.kt
version.gradle.kts

This PR adds `"com.intellij.treeCopyHandler"` extension point when creating PSI environment.
The point was requested when modifying PSI elements in McJava codegen.

Add `com.intellij.treeCopyHandler` extension point to PSI initialization

---

dependencies.md
plugin-testlib/src/main/kotlin/io/spine/tools/gradle/testing/BuildSrcCopy.kt
plugin-testlib/src/test/kotlin/io/spine/tools/gradle/testing/BuildSrcCopySpec.kt
pom.xml
tool-base/src/main/java/io/spine/tools/java/code/column/ColumnAccessor.java
version.gradle.kts

This PR changes the behaviour of `BuildSrcCopy`, so that integration tests using this tool could speed up their build time by using `buildSrc.jar` (an artifact assembled by Gradle) instead of re-compiling the `buildSrc` source files again.
For that, a dependency onto this JAR should be added to the `buildSrc`-build script of the respective integration-testing project. In future PR to `config`, some changes will be done to this file as well.
The API of `BuildSrcCopy` has been changed in several aspects: 
* By default:
*  `<original project root>/buildSrc/build/libs/buildSrc.jar` is copied to the **root** (!) of the target folder set for `BuildSrcCopy`. It is expected that the original `buildSrc.jar` will always be in place at the moment copying (which is usually during some integration …

Use `buildSrc.jar` when copying `buildSrc` folder during IG testing

---

dependencies.md
plugin-testlib/src/main/kotlin/io/spine/tools/gradle/testing/GradleProject.kt
plugin-testlib/src/main/kotlin/io/spine/tools/gradle/testing/GradleProjectSetup.kt
plugin-testlib/src/main/kotlin/io/spine/tools/gradle/testing/RootProject.kt
plugin-testlib/src/test/kotlin/io/spine/tools/gradle/testing/SourcesSpec.kt
pom.xml
version.gradle.kts

This changeset improves the `GradleProject` API used for testing.
In particular:
* `copyBuildSrc(...)` is now equipped with `cachingEnabled: Boolean = true` argument, which tells whether `buildSrc` sources should be used as-is, or a `buildSrc.jar` should be used instead;
* `GradleProjectSetup.withSharedTestKitDirectory()` points the TestKit runners to a single folder, `<root dir>/.gradle-test-kit` by convention; the idea is that this folder is not deleted on `gradlew clean` phase, and therefore may be somewhat re-used to speed up the test execution.

Improve `GradleProject` API for build speed

---

dependencies.md
pom.xml
psi-java/build.gradle.kts
version.gradle.kts

This PR promotes the dependency on `com.jetbrains.intellij.java:java-impl` from `implementation` to `api` so that tools can use `JavaCodeStyleSettings` and other Java-related types from the `com.intellij.psi.codeStyle` package.

Expose `IntelliJ.Java.impl` at `api` level

---

build.gradle.kts
dependencies.md
pom.xml
psi-java-bundle-jar/build.gradle.kts
version.gradle.kts

This PR attempts to solve the publishing problem, which was revealed during the publishing of the previous PR (#76).
The PR was not published at GitHub artifacts because it was not included into the `spinePublishing` list. 
We do not want to include the `psi-java-bundle-jar` module into regular publishing because we don't want to have all other artifacts (like source code JAR) produced for this module.
This PR makes the root `publish` task depend on the local `publish` task so that the module is finally published.

Force publishing of `psi-java-bundle`

---

build.gradle.kts
dependencies.md
pom.xml
psi-java-bundle-jar/build.gradle.kts
version.gradle.kts

This PR attempts to fix the problem with publishing of `psi-java-bundle` artifact by passing the corresponding module to `modulesWithCustomPublishing` of `spinePublishing`.
The previous method did not work because `CustomPublicationHandler` was not assigned.

Use custom publishing for `psi-java-bundle-jar`

---

buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/Publications.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/SpinePublishing.kt
dependencies.md
pom.xml
psi-java-bundle-jar/build.gradle.kts
version.gradle.kts

This PR fixes the duplicated `spine-` prefix assigned to the `psi-java-bundle` artifact.
Changes made to the `buildSrc` code would be propagated to `config` sometime next week.

Fix duplicated artifact prefix

---

buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/Publications.kt
buildSrc/src/main/kotlin/write-manifest.gradle.kts
dependencies.md
pom.xml
psi-java-bundle-jar/build.gradle.kts
tool-base/src/main/kotlin/io/spine/tools/code/manifest/KManifest.kt
version.gradle.kts

This PR teaches `SpinePublishing` to apply Gradle project description to `pom.xml` file created when publishing the project.
`psi-java-bundle` got the property to overcome the GitHub issue which picks up the description of Guava.
`KManifest` also got the property `bundleDescription` for possible future use.

Use project description in `MavenPublication`

---

buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
dependencies.md
pom.xml
psi-java/src/main/kotlin/io/spine/tools/psi/java/PsiClassExts.kt
psi-java/src/main/kotlin/io/spine/tools/psi/java/PsiElementFactoryExts.kt
psi-java/src/main/kotlin/io/spine/tools/psi/java/PsiModifierListOwnerExts.kt
psi-java/src/test/kotlin/io/spine/tools/psi/java/PsiClassExtsSpec.kt
psi-java/src/test/kotlin/io/spine/tools/psi/java/PsiElementFactoryExtsSpec.kt
psi-java/src/test/kotlin/io/spine/tools/psi/java/PsiModifierListOwnerExtsSpec.kt
version.gradle.kts

This PR brings extensions to PSI classes previously adopted in McJava.
* `addFirst()`.
* `createPrivateConstructor()`
* `createJavadoc()`
* `createStubMethod()`.
* `hasModifier()`
* `isPrivate`
* `isStatic` — now serves instead of `PsiClass.isStatic`, which was removed.
* `makeStatic()` — now serves instead of `PsiClass.makeStatic()`, which was removed.

Bring PSI-related extensions from McJava

---

dependencies.md
pom.xml
psi-java/src/main/kotlin/io/spine/tools/psi/java/Environment.kt
psi-java/src/test/kotlin/io/spine/tools/psi/java/EnvironmentReformatSupportSpec.kt
psi/src/main/kotlin/io/spine/tools/psi/ComponentManagerExts.kt
version.gradle.kts

This PR add registration of an `Application` service `MemberOrderService` which was discovered as a necessity for adding a supertype for `PsiClass` when extending McJava.

Add `MemberOrderService` when creating `Environment`

---

dependencies.md
pom.xml
psi-java/src/main/kotlin/io/spine/tools/psi/java/PsiElementFactoryExts.kt
version.gradle.kts

This PR adds `PsiElementFactory.createClassType()` inline function which makes creating a `PsiClassType` by fully qualified Java class name shorter than it natively available from PSI.

Add `PsiElementFactory.createClassType<T>()` extension

---

dependencies.md
plugin-base/src/main/kotlin/io/spine/tools/gradle/project/ProjectExts.kt
pom.xml
version.gradle.kts

This changeset updates the way in which we access the source sets of a Gradle `Project`.
Prior to this PR, we have relied upon `JavaPluginExtension.sourceSets` property. However, it only appeared in Gradle 7.1. So for Spine 1.9.x working on Gradle 6.9.x, an attempt to apply ProtoData or any other plugin based `tool-base`s code, results in `NoSuchMethodError`.
This pull request appends a fallback: if `NoSuchMethodError` is risen upon reading `sourceSets`, we now use a designated approach for Gradle versions prior to 7.1:
```kotlin
project.convention
.getByType(JavaPluginConvention::class.java)
.sourceSets
```
This API is now deprecated by Gradle, so a respective warning was suppressed.
The version of the library is set to `2.0.0-SNAPSHOT.214`.

Expose `Project`'s source sets for Gradle versions prior to 7.1.

---

buildSrc/src/main/kotlin/io/spine/internal/dependency/Clikt.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/IncrementGuard.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/PublishingRepos.kt
dependencies.md
pom.xml
version.gradle.kts

This PR fixes the publishing issue we used to experience in this repository _when_ the version was not incremented in `version.gradle.kts`.
The problem was that the version was checked agains artifacts published to CloudRepo which we do not publish to for some time. Because of that the problem was that the version of `tool-base` was way ahead of anything published CloudRepo, and `CheckVersionIncrement` task always passed the current version.
This PR changes the destination repository to `CloudArtifactRegistry.repository`.

Fix checking of version increment

---

dependencies.md
plugin-base/src/main/kotlin/io/spine/tools/gradle/Multiple.kt
plugin-base/src/main/kotlin/io/spine/tools/gradle/Ordered.kt
plugin-base/src/test/kotlin/io/spine/tools/gradle/MultipleSpec.kt
plugin-base/src/test/kotlin/io/spine/tools/gradle/OrderedSpec.kt
pom.xml
version.gradle.kts

This PR adds the `Ordered` class which is implementation of Gradle's `ListProperty`. The class is to accompany earlier introduced `Multiple` implementation of the `SetProperty` interface but for the cases when the order of items is important.

Introduce `Ordered` wrapper for `ListProperty`

---

dependencies.md
pom.xml
psi-java/src/main/kotlin/io/spine/tools/psi/java/PsiClassExts.kt
psi-java/src/main/kotlin/io/spine/tools/psi/java/PsiElementFactoryExts.kt
psi-java/src/main/kotlin/io/spine/tools/psi/java/PsiJavaFileExts.kt
psi-java/src/main/kotlin/io/spine/tools/psi/java/PsiModifierListOwnerExts.kt
psi-java/src/test/java/io/spine/tools/psi/java/PsiClassExtsJavaApiSpec.java
psi-java/src/test/java/io/spine/tools/psi/java/package-info.java
psi-java/src/test/kotlin/io/spine/tools/psi/java/PsiClassExtsSpec.kt
version.gradle.kts

This PR adds extension functions for `PsiClass` that allow to make a class implement certain interface and test if it already implements this or other interfaces.
* `implementsInterfaces()` — does the class implement any interface?
* `implements(PsiJavaCodeReferenceElement)` — does it implement this interface?
* `implement(PsiJavaCodeReferenceElement` — make this class implement this interface.
* The function `PsiClass.addSuperclass` was deprecated in favour or the new function called `setSuperclass`. The previous name was somewhat misleading because (thankfully) Java does not have multiple inheritance of classes.
* Added `@JvmName` for several extension functions.
* Annotated several extensions of `PsiModifierListOwner` with `@CanIgnoreReturnValue` where appropriate.

`PsiClass` extensions for implementing interfaces

---

dependencies.md
pom.xml
psi-java/src/main/kotlin/io/spine/tools/psi/java/PsiElementFactoryExts.kt
version.gradle.kts

This PR adds yet another extension function `PsiElementFactory.createClassReference()` in addition to one which accepts `vararg`.
Also, this PR deprecates the function which accepts `context` as the first parameter in favour of new one where the parameter comes last.

Overload `createClassReference` ext. fun for accepting `Iterable<String>` for generic params

---

dependencies.md
plugin-testlib/src/main/kotlin/io/spine/tools/gradle/testing/GradleProject.kt
plugin-testlib/src/test/kotlin/io/spine/tools/gradle/testing/GradleProjectSpec.kt
plugin-testlib/src/test/resources/failing_build/build.gradle.kts
pom.xml
psi-java/src/test/java/io/spine/tools/psi/java/PsiClassExtsJavaApiSpec.java
version.gradle.kts

This PR improves the code of `GradleProject.executeTask()` method to provide more diagnostics when the task execution fails.
Before this PR, calling `GradleRunner.build()` could result in throwing `UnexpectedBuildFailure` exception, and the output of the failed build was not available. Now the `UnexpectedBuildFailure` is caught and propagated via `IllegalStateException` which contains the project directory, task name, and the failed build output as the message of the wrapping exception.

Add diagnostics for failed Gradle builds

---

buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
dependencies.md
pom.xml
psi-java-bundle-jar/build.gradle.kts
version.gradle.kts

This PR updates the dependency on `spine-reflect` so that recently introduced improvements are added to the `spine-psi-java-bundle` artifact. Otherwise, the latest version of `reflect` could not be used from McJava.

Bump `reflect`

---

buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
dependencies.md
pom.xml
psi-java/src/main/kotlin/io/spine/tools/psi/java/JrtFileSystem.kt
version.gradle.kts

This PR advances the version of Base so that newer `options.proto` and related generated classes got into code generation tools. 
Also, the documentation of `JrtFileSystem` class was updated to address warnings in documentation.

Bump Base, address warnings in docs

---

buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
dependencies.md
pom.xml
version.gradle.kts

This PR bumps `spine-base` dependency, so that the assembled fat jar contains the latest version.

Bump `spine-base` dependency

---

buildSrc/src/main/kotlin/io/spine/internal/dependency/ProtoData.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
dependencies.md
pom.xml
psi-java/src/main/kotlin/io/spine/tools/psi/java/PsiClassExts.kt
psi-java/src/test/kotlin/io/spine/tools/psi/java/PsiClassExtsSpec.kt
version.gradle.kts

This PR fixes the extension of `PsiClass` that obtains a package name of the class. Previously, the extension did not work for nested classes, causing infinite loop.

Fix `PsiClass.packageName` extension

---

dependencies.md
intellij-platform-java/build.gradle.kts
intellij-platform/build.gradle.kts
pom.xml
version.gradle.kts

This PR updates the build scripts to publish two fat JARs: one for `intellij-platform` and another for `intellij-platform-java`. The second JAR would have only Java-related code thus requiring the presence of `intellij-platform` in the classpath.

Two JARs for IntelliJ Platform

---

buildSrc/src/main/kotlin/intellij-platform-jar.gradle.kts
buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/Publications.kt
dependencies.md
pom.xml
version.gradle.kts

This PR disables the `jar` task in modules related to IntelliJ Platform to avoid the Gradle task dependency error, which occurs after migrating to `8.10.2`.

Fix publishing task dependencies

---

dependencies.md
pom.xml
psi-java/src/main/kotlin/io/spine/tools/psi/java/PsiCommands.kt
version.gradle.kts

This PR wraps the `runnable` we give to PSI into a `try-catch` block, with the configurable possibility to throw right away.
We need this change, so that users of ProtoData could see these errors.
I have tested this approach locally with changes to `tool-base` and `ProtoData`, it works. And I have not found any usages of `commandProcessor.executeCommand()` out of this extension, which we use as an entry point to PSI modifications.
Addresses problem (2) described in [this](https://github.com/SpineEventEngine/core-java/pull/1564#issuecomment-2582440484) comment.

Redirect PSI errors to the default exception handler

---

dependencies.md
pom.xml
psi-java/src/main/kotlin/io/spine/tools/psi/java/PsiClassExts.kt
psi-java/src/main/kotlin/io/spine/tools/psi/java/PsiElementExts.kt
psi-java/src/main/kotlin/io/spine/tools/psi/java/PsiStatements.kt
psi-java/src/test/kotlin/io/spine/tools/psi/TestFixtures.kt
psi-java/src/test/kotlin/io/spine/tools/psi/java/PsiClassExtsSpec.kt
psi-java/src/test/kotlin/io/spine/tools/psi/java/PsiElementExtsSpec.kt
psi-java/src/test/kotlin/io/spine/tools/psi/java/PsiStatementsSpec.kt
version.gradle.kts

This PR moves PSI extensions from `validation` library, covering them with tests.

Move extensions from `validation` library

---

.idea/inspectionProfiles/Project_Default.xml
.idea/kotlinc.xml
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/io/spine/dependency/build/Dokka.kt
buildSrc/src/main/kotlin/io/spine/dependency/build/Ksp.kt
buildSrc/src/main/kotlin/io/spine/dependency/lib/Auto.kt
buildSrc/src/main/kotlin/io/spine/dependency/lib/Kotlin.kt
buildSrc/src/main/kotlin/io/spine/dependency/lib/KotlinPoet.kt
buildSrc/src/main/kotlin/io/spine/dependency/lib/KotlinX.kt
buildSrc/src/main/kotlin/io/spine/dependency/local/Base.kt
buildSrc/src/main/kotlin/io/spine/dependency/local/Logging.kt
buildSrc/src/main/kotlin/io/spine/dependency/local/McJava.kt
buildSrc/src/main/kotlin/io/spine/dependency/local/ProtoData.kt
buildSrc/src/main/kotlin/io/spine/dependency/local/Spine.kt
buildSrc/src/main/kotlin/io/spine/dependency/local/TestLib.kt
buildSrc/src/main/kotlin/io/spine/dependency/local/Time.kt
buildSrc/src/main/kotlin/io/spine/dependency/local/ToolBase.kt
buildSrc/src/main/kotlin/io/spine/dependency/local/Validation.kt
buildSrc/src/main/kotlin/io/spine/dependency/test/KotlinCompileTesting.kt
buildSrc/src/main/kotlin/io/spine/gradle/publish/CheckVersionIncrement.kt
buildSrc/src/main/kotlin/io/spine/gradle/publish/SpinePublishing.kt
dependencies.md
pom.xml
psi-java/src/main/kotlin/io/spine/tools/psi/java/PsiCommands.kt
version.gradle.kts

This PR changes the behaviour for the error handler passed as the default handler to the `execute` function for running PSI commands.
Previously, the handler printed the stack trace of the exception and existed the process with the code 1. This proved to be way too hard for testing and debugging cases of compilation that deal with errors. Tests were just reported as ignored because the Java process exited in the middle of "nowhere" from the JUnit's perspective.
The new behaviour just rethrows the caught `Throwable`. This addresses the issue with silent swallowing which was a problem with the default behaviour of the `execute` block when the error handler was introduced. Yet, not existing the process and not printing the stacktrace to console makes the handler less intrusive for the users.

Ease default handler on `execute` of PSI commands

---

dependencies.md
plugin-base/src/main/kotlin/io/spine/tools/gradle/protobuf/SourceSetExts.kt
plugin-base/src/main/kotlin/io/spine/tools/gradle/task/SourceSetExts.kt
pom.xml
version.gradle.kts

This PR applies the `findXxx()` convention to the existing extension functions that return nullable types. Also, the `SourceSet.findKotlinDirectorySet()` extension function was introduced in the `task` package, deprecating the one which does the same but wrongly placed under the `protobuf` package.

More on extensions

---

buildSrc/src/main/kotlin/io/spine/gradle/publish/GitHubPackages.kt
buildSrc/src/main/kotlin/io/spine/gradle/publish/PublicationHandler.kt
buildSrc/src/main/kotlin/io/spine/gradle/publish/PublishingExts.kt
buildSrc/src/main/kotlin/io/spine/gradle/publish/SpinePublishing.kt
buildSrc/src/main/kotlin/io/spine/gradle/publish/StandardJavaPublicationHandler.kt
buildSrc/src/main/kotlin/io/spine/gradle/repo/Repository.kt
dependencies.md
pom.xml
version.gradle.kts

This PR continues the efforts of fighting with the failed publishing jobs. Hopefully, we nailed it this time. 
The publication code under `buildSrc` was traced agains the local publishing and it was discovered that the adding destination directories for a publication that we called on `Project.afterEvaluate` was executed twice. The reason for calling the actions put under `afterEvaluate` more than once is unknown. Also, there is not guaranty that this behaviour is stable from version to version of Gradle, so we took the approach of remembering the state under the `synchronized` block.
The duplication of target repositories always worked this way. It's only recently that we started experiencing this under the `tool-base` repository because the fat JAR of IntelliJ IDEA platform is a big …

Avoid duplicated repositories when arranging custom module publication

---

dependencies.md
pom.xml
tool-base/build.gradle.kts
version.gradle.kts

This PR restores setting the duplication strategy for the `sourcesJar` task the absence of which [failed the publication](https://github.com/SpineEventEngine/tool-base/actions/runs/14672057423/job/41180619595) of the previous PR.
The absence of the duplication strategy does not reveal itself on the local publishing. The way it was set before failed the build because the `sourcesJar` task was not available on `afterEvaluate`.
Now the setting of the duplication strategy is done via `configureEach`, which is a safe approach, which is not affected by the presence of the task.

Restore setting duplication strategy for `:tool-base:sourcesJar` task

---

buildSrc/src/main/kotlin/io/spine/dependency/lib/Kotlin.kt
dependencies.md
plugin-base/src/main/kotlin/io/spine/tools/gradle/protobuf/ProjectExts.kt
pom.xml
version.gradle.kts

This PR uses the new "generous" capability of the `ProtobufExtension` class which now has the method `getGeneratedFilesBaseDir()` public. This allows us to obtain the path into which `protoc` places the code.
It should be noted that the value of the property changed, making ProtoData [exit silently](https://github.com/SpineEventEngine/ProtoData/issues/349) without generating any code.
The new version of ProtoData would be based on the version of ToolBase produced by this PR.

Migrate to new Protobuf Gradle Plugin API

---

buildSrc/src/main/kotlin/io/spine/dependency/lib/Protobuf.kt
buildSrc/src/main/kotlin/io/spine/dependency/local/Base.kt
buildSrc/src/main/kotlin/io/spine/gradle/publish/PublicationHandler.kt
dependencies.md
plugin-base/src/main/kotlin/io/spine/tools/gradle/protobuf/ProjectExts.kt
plugin-base/src/test/kotlin/io/spine/tools/gradle/PluginBaseDependencyVersionsSpec.kt
pom.xml
version.gradle.kts

This PR provides compatibility mode for working with Protobuf Gradle Plugins before `0.9.5` and after.
The run-time version of Protobuf library was rolled back from `4.30.2` to `3.25.7` — which is the last version of the `3.x` family  — so that we can migrate tools that depend on older API based on `GeneratedMessageV3` type.
* The `SpinePublishing` was fixed to ensure publication to `mavenLocal()` between consequent builds. It was discovered that the singleton cache we have for `PublicationHandler`s survives between consequent builds, if the content of `buildSrc` was not modified.

Support older and newer Protobuf Gradle Plugins at the same time

---

dependencies.md
pom.xml
psi-java/src/main/kotlin/io/spine/tools/psi/java/PsiElementExts.kt
version.gradle.kts

This PR fixes an issue with diagnostics of a non-found PSI element child. Previously, the message for a thrown exception was looking like this:
```
Message: io.spine.tools.psi.java.PsiElementExtsKt$$Lambda$905/0x000000b8017993d0@2f6b60ee
```
This was caused by the typo in the code when the argument for the `error()` function was a lambda calculating the message. The lambda did not evaluate when `error()` was called because its `toString()` was called instead of `invoke()`.
The PR addresses this issue by adding more diagnostics to help with discovering issues during migration of Validation and McJava to new Protobuf v4.31.0.

Fix error message for non-found PSI element child

---

dependencies.md
jvm-tool-plugins/src/main/kotlin/io/spine/tools/gradle/jvm/plugin/ArtifactMetaExtension.kt
jvm-tool-plugins/src/main/kotlin/io/spine/tools/gradle/jvm/plugin/ArtifactMetaPlugin.kt
jvm-tool-plugins/src/main/kotlin/io/spine/tools/gradle/jvm/plugin/WriteArtifactMeta.kt
jvm-tool-plugins/src/test/kotlin/io/spine/tools/gradle/jvm/plugin/ArtifactMetaPluginSpec.kt
pom.xml
version.gradle.kts

This PR extends `artifactMeta` DSL with an ability to add dependencies explicitly. Since only immediate dependencies are added, this DSL is needed for adding transitive dependencies such as Google Protobuf `protoc` artifact.

Allow adding explicit dependencies in `artifactMeta`

---

dependencies.md
jvm-tool-plugins/src/main/kotlin/io/spine/tools/gradle/jvm/plugin/ArtifactMetaExtension.kt
jvm-tool-plugins/src/main/kotlin/io/spine/tools/gradle/jvm/plugin/ArtifactMetaPlugin.kt
jvm-tool-plugins/src/main/kotlin/io/spine/tools/gradle/jvm/plugin/WriteArtifactMeta.kt
jvm-tool-plugins/src/test/kotlin/io/spine/tools/gradle/jvm/plugin/ArtifactMetaPluginSpec.kt
pom.xml
version.gradle.kts

This PR extends the `artifactMeta` DSL with an ability to set a custom `artifactId`.
The default value for the ID is `project.name`. Overriding the default value is necessary when the project is published with the ID other than its name.

Allow custom artifact ID in `artifactMeta`

---

dependencies.md
gradle-root-plugin/src/main/kotlin/io/spine/tools/gradle/root/ProjectExts.kt
pom.xml
version.gradle.kts

This PR makes the `Project.rootExtension` search for an extension by its type (`RootExtension`). Previously, it was searched by its name (`"spine"`) which clashed with custom version catalog created in the previous version of the `BuildSpeed` project. 
Even though Gradle is not likely to allow multiple extension with the same name, the type-safe way for obtaining an extension would save on debugging time when a potential clash occurs next time.

Find root extension by type

---

dependencies.md
jvm-tools/src/main/kotlin/io/spine/tools/meta/LazyMeta.kt
jvm-tools/src/test/kotlin/io/spine/tools/meta/LazyMetaSpec.kt
jvm-tools/src/test/resources/META-INF/io.spine/test.group_test-artifact.meta
pom.xml
version.gradle.kts

This PR introduces `LazyMeta` and `LazyDependency` classes that were adopted while working on [this PR in CoreJvm Compiler](https://github.com/SpineEventEngine/core-jvm-compiler/pull/13).
The classes simplify working with the `ArtifactMeta` instances at the usage sites.

Introduce `LazyMeta` and `LazyDependency` classes
